requirements.txt

elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch

downgrading elasticsearch client. the latest version throwing

---

openshift/template.yaml

This was causing a failure to deploy the template:
```
error fetching template: mapping values are not allowed here
in "<byte string>", line 77, column 26:
valueFrom:
```

Fix kibana env indentation

---

openshift/template.yaml

Section starts with "--" shouldn't have an escaping
Cause: "unable to decode review: invalid character '\'' looking for beginning of value"

Removing invalid quote

---

openshift/template.yaml

The NAMESPACE param used for Kibana oauth2 proxy
only users with access to the namespace kibana-proxy service can access the Kibana instance

Adding NAMESPACE param definition to the template

---

openshift/template.yaml

follows up on #35, #37
instead of supplying the namespace from the outside, the container can get it from the pod's metadata.
ref: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables

get namespace from pod metadata

---

docs/deployment.md
openshift/template.yaml

Current situation:
* we are using AWS elasticsearch service
* we are deploying our own in-cluster kibana instance, connected with AWS elasticsearch endpoint
* in front of kibana we use OAuth proxy for authorization
This change aims to simplify the architecture of the app by removing an unnecessary component: in-cluster kibana.
Instead of it, we will directly forward AWS's kibana console through OAuth proxy.

Proxy AWS opendistro dashboard directly

---

README.md
assisted-events-scrape/events_scrape/events_scrape.py
openshift/template.yaml
requirements.txt

The purpose of this PR is to add sentry.io to this project.
The logic is that if env var `SENTRY_DSN` is not defined, the application will behave as it did before this change.
If it is set, we will register all exceptions, so that we can make sure all issues are addressed.
Errors will be found at this dashboard https://sentry.stage.devshift.net/sentry/assisted-events-scrape-stage/
This has been tested in integration, by swapping values that would be set in stage.
@michaellevy101  it appears that there is no sentry team defined for integration - is this done on purpose? Or shall we activate integration sentry too?

add sentry

---

README.md
assisted-events-scrape/events_scrape/events_scrape.py
openshift/template.yaml

The aim of this PR is to try reduce inconsistencies we have between elastic data and sql production data.
At the moment we are missing lots of events:
* looping through cluster should take several minutes
* however, sometimes it never happens. if we throw an exception it might raise to the first loop, and restart the process from step 1 (retrieving all clusters). This means that if we get to another exception, we restart. Some unlucky clusters can take days to show up its events
* particularly problematic the case of quick registration and deregistration of clusters. As we do not retrieve unregistered clusters, we'll never receive any events for this case
* another scenario is when a cluster is deregistered, as we are not currently listing all clusters, we'll miss all events from …

improve error handling and data collection

---

openshift/template.yaml

This is fixed in https://github.com/openshift-assisted/assisted-events-scrape/pull/49 (from both code and default value for env vars).
This PR is needed to fix deployments in the meantime the other PR will get merged

add default values for env var, as empty string breaks the code

---

README.md
assisted-events-scrape/events_scrape/events_scrape.py
assisted-events-scrape/events_scrape/logger.py
requirements.txt

This PR aims to improve parseability of logs by switching to JSON logging.
This way we will be able to better parse logs, faster filters, and better information in the grafana dashboards
from:
```
2022-03-17 08:57:26,390 INFO       - 140295224396672 - 217/410: Starting process of cluster 896396a3-fd0d-41a1-b9a8-bacfc1464b05 	(/usr/local/lib/python3.6/site-packages/events_scrape/events_scrape.py:93)
2022-03-17 08:57:26,418 INFO       - 140295224396672 - 218/410: Starting process of cluster 5241b682-0557-48b1-9687-a4282ff0a337 	(/usr/local/lib/python3.6/site-packages/events_scrape/events_scrape.py:93)
2022-03-17 08:57:26,458 INFO       - 140295224396672 - Downloading cluster events to /tmp/tmpz6g3y73b 	(/usr/local/lib/python3.6/site-packages/events_scrape/assisted_service_api.py:381)
``` …

MGMT-9468: add json logging for better parsing

---

requirements.txt

We should and will upgrade the client as soon as possible, but for now let's make sure this app actually runs.

fix client version to avoid erros

---

OWNERS_ALIASES

Update with people that are actually working on the project: we avoid spamming on other teammates mail and get relevant people on the review.

change owners

---

assisted-events-scrape/config/scraper_config.py
assisted-events-scrape/events_scrape/events_scrape.py
assisted-events-scrape/repositories/event_repository.py
assisted-events-scrape/storage/cluster_events_storage.py

Remove unused code:
* "backups" are done in ephemeral disks, and have never been used. Not sure how we'd be supposed to use them anyways
* Removed unnecessary disk operations when retrieving events

remove unused code

---

Makefile
tools/deploy_manifests.sh
tools/get_ocp_route_host.sh

The aim of this PR is to fix a few details about integration testing in CI.
Once merged, when `make ci-integration-test` is run from CI should successfully run integration tests.

fix CI integration test

---

dashboards/grafana-dashboard-assisted-elasticsearch.configmap.yaml
dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml

Moving event-scraper grafana dashboards from assisted-service. steps;
* add dashboards to events-scrape (this PR)
* remove dashboards from assisted-service
* deploy dashboards from both projects

add grafana dashboards (moved from assisted-service)

---

Dockerfile.elasticdump
Makefile
build_deploy.sh

According to App-SRE is best practice to avoid docker.io mirroring.
Instead, it is recommended to rebuild this image from a trusted source.

rebuild elasticdump image

---

openshift/template.yaml

Changing default index to restore.
Similar PRs will follow to keep the migration going.

historical data restore: only load march 2021 to start with

---

openshift/template.yaml

This is needed if we override tag (as we did)

parametrise image pull policy for job

---

.ci-operator.yaml

This uses valid syntax for build root. Leaving a default image here, but in the future it can be change within the repo instead of having to open a `release` PR

use default build_root image

---

.ci-operator.yaml

Remove CI operator config, now unnecessary

use centos as build_root image

---

assisted-events-scrape/config/event_store.py
assisted-events-scrape/storage/elasticsearch_storage.py
assisted-events-scrape/storage/object_storage_writer.py
assisted-events-scrape/tests/integration/test_elasticsearch_storage.py
assisted-events-scrape/tests/unit/test_cluster_events_worker.py
assisted-events-scrape/workers/cluster_events_worker.py
openshift/template.yaml
requirements.txt

the aim of this PR is to remove some fields from cluster metadata when determining the checksum. This will help us reducing the number of cluster events due to unnecessary fields

ignore cluster fields in checksum, to avoid frequent status changes

---

openshift/template.yaml

These fields change very frequently, we do not need to monitor such change

add fields to cluster events ignored fields list

---

openshift/template.yaml

We'll ignore inventory when calculating if the cluster changed.
We will store it nevertheless (just when something else change, we'll store the current inventory)

add hosts.inventory to ignored fields

---

assisted-events-scrape/config/object_storage.py

Cronjob fails without protocol.
Minio needs http, this should be good with `s3://`

add default protocol

---

assisted-events-scrape/workers/cluster_events_worker.py

This avoids calculating different hash when only the order is different

order hosts when calculating checksum

---

openshift/template.yaml

Lets filter more fields and see if we can get rid of a couple of cases where host keeps updating ntp sources causing thousands of events

add more fields to ignore

---

openshift/template.yaml

This was a workaround to expose elasticsearch to applications. We would save applications' credentials in the htpasswd file, and we could provide service from there. However this method has been deemed insecure by AppSRE and we should remove it

remove basic auth on oauth proxy

---

assisted-events-scrape/tests/integration/test_integration.py
assisted-events-scrape/workers/cluster_events_worker.py

When saving enriched event we want to have `infra_env` as a property of cluster object, however when saving normalized events, we do not want it.
The code was mistakenly modifying the original object, thus not saving infra_env values in the events.

bugfix: do not modify cluster event object

---

assisted-events-scrape/storage/cluster_events_storage.py
assisted-events-scrape/tests/integration/test_integration.py
elasticsearch/templates/assisted-service-events.json
requirements.txt

- Remove user_name from cluster object (elastic)
- Set unique user_id using FNV-1a 128bit algorithm instead (not reversible)
/cc @rccrdpccl

MGMT-10912 - Remove `user_name` from cluster object

---

assisted-events-scrape/tests/integration/test_integration.py
assisted-events-scrape/workers/cluster_events_worker.py

After all it was not such a great idea to standardize this field, as UUID5 generates way too many collisions for this.
Let's stick to the original checksum

remove UUID5 conversion, as it generates collisions

---

Dockerfile.build

The service of mirror.openshift.org is sometimes not responding well enough to our fetching logic in assisted-events-scrape build's dockerfile:
```
STEP 8/14: RUN curl -sS -o oc-${OC_VERSION}.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.10.8/openshift-client-linux-${OC_VERSION}.tar.gz &&    tar xzvf oc-${OC_VERSION}.tar.gz &&    install kubectl /usr/local/bin/kubectl &&    install oc /usr/local/bin/oc &&    rm -f oc-${OC_VERSION}.tar.gz README.md kubectl oc599600gzip: stdin: unexpected end of file601tar: Child returned status 1602tar: Error is not recoverable: exiting now 
```
Example: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-assisted_assisted-events-scrape/127/pull-ci-openshift-assisted-assisted-events-scrape-master-images/15 …

MGMT-11686: install oc and kubectl from docker image

---

openshift/template.yaml

Enable the ability to suspend cronjob from parameters.
This is useful if we want to temporarely suspend it without deploying a new version of the application (just changing params)

enable cron suspend

---

Dockerfile.build

Following the same philosophy of https://github.com/openshift-assisted/assisted-events-scrape/pull/128

take kubeconform from docker image instead of curl

---

assisted-events-scrape/ccx_export/__init__.py
assisted-events-scrape/ccx_export/delete_from_ccx_s3_bucket.py
openshift/template.yaml
setup.py

Did not take into account that we do not burn into the image /tools directory, as it is intended for helper tools only.
This PR moves the cleanup code to be actual production code

change cleanup command

---

tools/deploy_manifests.sh

Sometimes the jobs start too fast, before minio server, and they fail. They would eventually succeed, but we run tests before they have a chance to run again. Let's wait for them a couple of minutes, so we avoid failing a test that potentially would pass.

reduce flakiness of integration test: wait for minio jobs

---

assisted-events-scrape/storage/object_storage_writer.py

First two runs (purple and red lines) are with `del <object>` but not calling explicitly Garbage Collector, third run calls explicitly GC (yellow line).
The first run (bright yellow) in the chart above is explicit GC call with explicit call for `del <object>` , while the second (darker yellow) is explicit GC call without explicit `del <object>` call
This improves memory used and should help running the job with massive amount of data, although the job will run slower.

explicitly call GC

---

assisted-events-scrape/tests/integration/test_integration.py
assisted-events-scrape/tests/unit/test_cluster_events_worker.py
assisted-events-scrape/workers/cluster_events_worker.py

This exports event_id. useful to identify (and ignore) duplicates in other systems (i.e. CCX)

add event_id to event payload for export

---

openshift/template.yaml

Allocating resources should help guaranteeing the execution of the cron, as it consumes quite a lot of memory

parametrize resource requests and limits

---

assisted-events-scrape/storage/object_storage_writer.py
openshift/template.yaml

We still had one pod OOMKilled, so file buffering might be a better strategy here.

add file buffering to reduce memory consumption

---

README.md
assisted-events-scrape/config/elasticsearch.py
assisted-events-scrape/storage/cluster_events_storage.py
assisted-events-scrape/tests/integration/test_integration.py
elasticsearch/templates/assisted-service-events.json
openshift/template.yaml
tools/run_integration_test.sh

This PR aims at simplifying maintenance and increase performance:
* when a mistake in mapping makes it to the target environment, we need lengthy and sometimes complicated operations to fix it. If the mistake it's limited to the latest month, there is way less data to deal with making everything simpler. This is true not only for mistakes but for backups, migrations, etc... we could enable straight away latest months while restoring older dates, and most people would not be affected by this
* increase performance when searching in the last few months. It will be a bit more expensive for queries that include several months, as results will need to be merged

use suffixed indices for easier maintenance

---

dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml

This PR fixes the dashboard to reflect the alert and include multiple indices when counting events ingestion stats

fix events ingestion dashboard to include multiple indices

---

assisted-events-scrape/storage/cluster_events_storage.py
assisted-events-scrape/tests/integration/fixtures/events-fc124c08-f3a5-464f-834e-c262d9eb5a38.json
assisted-events-scrape/tests/integration/test_integration.py

At the moment we have the issue that we might stick duplicate data in the indices, as the current system relies on conflicts when inserting already downloaded data.
This change avoids that by just inserting events by date instead of time of indexing

date depends on data instead of time of indexing

---

assisted-events-scrape/tests/unit/test_cluster_events_worker.py
assisted-events-scrape/workers/cluster_events_worker.py

This is a quick fix to blacklist clusters.
Another PR will follow to make this functionality more flexible (also inject values from ENV vars)

drop blacklisted clusters

---

assisted-events-scrape/tests/unit/test_cluster_events_worker.py
assisted-events-scrape/workers/cluster_events_worker.py

Large clusters cause all kind of issues.
Not ideal to fetch hosts first, but it looks like it's the only way to know.

do not save large clusters

---

assisted-events-scrape/ccx_export/export_to_s3.py
assisted-events-scrape/events/events_exporter.py
assisted-events-scrape/tests/integration/test_events_exporter.py

This PR fixes a bug where we do not export unpartitioned data if we already exported it before (thus have an offset).
In the specific case, we are not exporting `component_versions` as data is unpartitioned (no cluster_id) and it has been exported before.
This bug has been introduced when we have changed the way we export data, only one version is missing for now.
Once fixed, it should be exported automatically.

fetch data for streams that are unpartitioned but they actually have an offset

---

openshift/template-autopromotion.yaml

Add template for autopromotion jobs
This will be executed after each deployment.
Variables will be set within the saas file, so that we won't publish internal addresses

add autopromotion template

---

openshift/template-autopromotion.yaml

Unfortunately the legacy code collecting events is not collecting enough, and sometimes it's triggering a failure in the condition.

improve autopromotion condition

---

assisted-events-scrape/utils/anonymizer.py

Not sure how this can happen but we got some of those errors:
Adding None as default value should get rid of KeyError

add logging to see what is causing anonymizer to break

---

assisted-events-scrape/events/events_exporter.py
assisted-events-scrape/storage/offset.py

CCX export is breaking because too many partitions are retrieved.
Although this repo is deprecated we need to fix it so exportable data won't accumulate, we'll later implement this export in the kafka based pipeline

fix ccx export
