- Makefile
- README.md
- events_scrap/events_scrap.py
- openshift/template.yaml
- utils/utils.py
Adding Openshift template will be used by the app-sre to deploy this service on the different environments
> MGMT-7947: Adding Openshift template

- Dockerfile
> Fix entrypoint of docker container

- README.md
- openshift/template.yaml
This PR is needed to enable:
* Proxying elasticsearch
* adding htpasswd file, where we can add programmatic users
> add system users to authorization system

- Makefile
- build_deploy.sh
This kibana image build is not needed anymore, and it's failing the build
> Remove unused build parameters

- Dockerfile
- Dockerfile.build
Revert "remove dnf update" change and switch to ubi-based image for production: reduces image size by ~800mb
> NO-ISSUE: reintroduce dnf updates and switch to ubi-minimal for prod

- Dockerfile
- Dockerfile.build
- requirements.txt
By not fixing the version we can get all sort of problems both in local build and production.
This PR aims to solve that issue
> fix version for dependencies

- openshift/template.yaml
> fix indentation of openshift manifest

- assisted-events-scrape/tests/integration/manifests/secrets.yaml
- openshift/template.yaml
The aim of this PR is to reduce number of secrets used, as a new one was introduced by mistake.
> use kibana-oauth-application

- Dockerfile.build
- Makefile
- openshift/template.yaml
Apparently replicas should be string, for then converting it into int :thinking: 
Added validation for openshift template, so we can catch this type of error before pushing changes (and we'll add it to CI when we'll get to that)
> fix parameter type

- Makefile
- assisted-events-scrape/utils/logger.py
- openshift/template.yaml
> add loglevel

- openshift/template.yaml
> add sentry release

- .kind/daemonset.yaml
- Dockerfile.build
- Makefile
- assisted-events-scrape/tests/integration/ci-manifests/elasticsearch-template.yaml
- assisted-events-scrape/tests/integration/manifests/elasticsearch.yaml
- assisted-events-scrape/tests/integration/manifests/mockserver.yaml
- tools/deploy_manifests.sh
- tools/generate_mockserver_configmap.sh
- tools/get_elasticsearch_endpoint.sh
- tools/get_ocp_route_host.sh
- tools/ocp2k8s.sh
The aim of this PR is to add a target in the makefile to be used from CI
https://github.com/openshift/release/pull/27646
> add makefile target for ci-integration-test

- openshift/template.yaml
- tools/deploy_manifests.sh
- tools/ocp2k8s.sh
This job will migrate historical data.
Data is divided by months. We will split the migration in different steps, as different months have different characteristics (more or less problematic).
We will start with the non-problematic ones
> add migration job

- build_deploy.sh
- openshift/template.yaml
- tools/ocp2k8s.sh
This PR aims at producing and using a valid image for app-sre deployment
> produce valid image for app-sre

- build_deploy.sh
The script won't work if we don't pull first... :facepalm:
> pull elasticdump image before tagging

- openshift/template.yaml
This reverts commit 6244c3c9d31a2e620ec024a4f0de76b464905ae4.
> Revert "temporarely remove job, so that app-sre build can succeed (#83)"

- Dockerfile.elasticdump
- openshift/template.yaml
The aim of this PR is to improve migration job's throughput, thus decrease running time
> improve migration job throughput

- openshift/template.yaml
> add missing semicolon

- .ci-operator.yaml
The aim of this PR is to add ci-operator config file, so then we can point to this from release
> add ci-operator config

- assisted-events-scrape/clients/elasticsearch.py
- assisted-events-scrape/events/events_exporter.py
- assisted-events-scrape/storage/cluster_events_storage.py
- assisted-events-scrape/storage/elasticsearch_storage.py
- assisted-events-scrape/storage/offset.py
- assisted-events-scrape/tests/integration/test_elasticsearch_storage.py
- assisted-events-scrape/tests/integration/test_integration.py
- requirements.txt
> switch to opensearch client

- assisted-events-scrape/config/object_storage.py
> actually use endpoint, with default protocol added when necessary

- openshift/template.yaml
Parametrize requests/limits: this way it can be changed directly from app-interface if needed
Adjusted values to actual usage (requests)
> assisted events scrape: parametrize and adjust resources requests/limits

- assisted-events-scrape/events/events_exporter.py
- openshift/template.yaml
Add debug message and set debug to default for exporter.
> add debug to ccx exporter

- assisted-events-scrape/events/events_exporter.py
An error gets thrown because of timeouts when scanning documents, I think we are retrieving so many that it's going past the normal timeout. Let's try with 30s
> increase timeout for scan requests

- tools/run_integration_test.sh
This should fix the problem of broken integration test in CI
> NO-ISSUE: only execute docker (get_endpoint.sh) for local env

- assisted-events-scrape/config/event_store.py
- assisted-events-scrape/storage/cluster_events_storage.py
- assisted-events-scrape/tests/integration/test_integration.py
- assisted-events-scrape/tests/unit/test_cluster_events_worker.py
- assisted-events-scrape/workers/__init__.py
- assisted-events-scrape/workers/cluster_events_worker.py
The checksum was being taken in the wrong point.
To make stuff clearer we have separated abit infra_env logic with cluster
> set correct hash for cluster_state_id

- dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml
Adding new panel to check events being scraped:
> add dashboard for events importing metrics

- assisted-events-scrape/storage/elasticsearch_storage.py
In some cases an event would have the same ID of an existing one (as we pull snapshots, this can happen, as IDs are not generated upstream).
The issue is that *some* (previously ignored) fields can be updated, and screw the import process, generating duplicates.
This PR fixes that issue by not overwriting already existing documents
> events with same ID should not be replaced

- assisted-events-scrape/storage/object_storage_writer.py
We get unexpectedly high memory usage, let's try to keep it low
> force free documents from memory

- assisted-events-scrape/events/events_exporter.py
- assisted-events-scrape/storage/offset.py
- assisted-events-scrape/tests/unit/test_offset.py
In some cases we get different date format, and we should handle it
> fix date aware and naive comparison

- openshift/template.yaml
Fix and set resource policies for cronjobs to ensure their execution
> set and fix resource policies for cronjobs

- Dockerfile
Like title says, upgrade to latest available tagged 8.x ubi image
> upgrade to ubi 8.6

- assisted-events-scrape/tests/integration/test_integration.py
- assisted-events-scrape/tests/unit/test_anonymizer.py
- assisted-events-scrape/utils/anonymizer.py
- assisted-events-scrape/workers/cluster_events_worker.py
User_name is currently not anonymized under infra_envs. This PR fixes that
> anonymize infra_envs

- Dockerfile.Kibana
Small cleanup and test autopromotion :)
> remove unnecessary Dockerfile

- Dockerfile
This slightly improves cache and resulting image size
> improve Dockerfile for production image

- requirements.txt
> OCPBUGSM-31129: Update urllib3 to the latest version

- dashboards/grafana-dashboard-assisted-elasticsearch.configmap.yaml
Just changing references as the dashboard used to reference hardcoded datasource and it change its ID
Signed-off-by: Riccardo piccoli <rpiccoli@redhat.com>
> fix elasticsearch dashboard
